apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
    role: master
    tier: backend
  name: policy-msql-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      role: master
      tier: backend
  template:
    metadata:
      labels:
        app: mysql
        role: master
        tier: backend
    spec:
      containers:
      - image: mysql:5.5
        name: policy-msql-master
        env: 
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef: 
              name: mysql-policy-secret
              key: password
        - name: mysqlpolicysvc
          value: mysqlpolicysvc  
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes: 
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-policy-pvc    
   
