apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
    role: master
    tier: backend
  name: mysqlpolicysvc
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql
    role: master
    tier: backend
